### ISSUE TITLE
one specific line has only one column; removing this line make the classifier work correctly.

### ISSUE THREAD

**Issue by lamastex** [klintan/swedish-ner-corpus#1]
I also did the following:
1. replace '0' by 'O' globally using ':%s/0/O/g' in $ vim training-data-file-name.txt
2. remove the blank lines using $ sed -i '/^$/d' training-data-file-name.txt
3. remove line 85124 as there is only one column in this line: 'Error on line 85124: bn' 

Then all is well as per:  https://medium.com/@klintcho/training-a-swedish-ner-model-for-stanford-corenlp-part-2-20a0cfd801dd

**Comment by lamastex** [comment]
BTW, It would be super if you showed step-by-step how you generated the training data (i.e., add he scripts to this GitHub repos so others can replicate and even improve upon your pipeline for generating training-data).

**Comment by klintan** [comment]
Thanks for you comments, I know it's almost 1.5 years ago :P haha.

Some information are here, https://github.com/klintan/gazetteer2trainingdata and the actual data here https://github.com/klintan/swedish-gazetteers.

edit: I wrote those scripts ages ago, so the code quality is shitty at best. But the data might be valuable.
