### ISSUE TITLE
License for the annotation data?

### ISSUE THREAD

**Issue by tellarin** [klintan/swedish-ner-corpus#2]
What is the current license for the annotation data?

Creative Commons "Attribution 4.0 International" (https://creativecommons.org/licenses/by/4.0/) may be a good choice as the source (https://spraakbanken.gu.se/eng/resource/webbnyheter2012) is already licensed as CC-BY.

Could you please add a LICENSE file to the repo clarifying it?

Thanks!

**Comment by klintan** [comment]
Thanks for your suggestion, yes I added that license to clarify.
