### ISSUE TITLE
Relation to kaggle Swedish NER corpus

### ISSUE THREAD

**Issue by AngledLuffa** [klintan/swedish-ner-corpus#4]
You had once made a Kaggle Swedish NER corpus:

https://www.kaggle.com/andreasklintberg/swedish-ner-corpus

Is this newer?  The date is slightly more recent, after all.  Thanks!

**Comment by klintan** [comment]
Yes there was a PR for this one made https://github.com/klintan/swedish-ner-corpus/pull/3 which I don't think is included in the Kaggle Dataset.
